### ISSUE TITLE
Android back button should just close the post window, instead of close Jumber

### ISSUE THREAD

**Issue by bitcoinuser** [CodyTseng/jumble#16]
Hi, 

Android back button should just close the post window, instead of close Jumber. See the video:

https://github.com/user-attachments/assets/3eb07d82-7bfd-4aa4-9321-706694949739

**Comment by bitcoinuser** [comment]
Other example. If I open a thread and click android back button, works ok, go to main window. But if I click on a thread and then pulldown to refresh and click android back button, Jumber close. See the video:

https://github.com/user-attachments/assets/98239fc4-9152-461a-9158-3896eeaac51d

**Comment by CodyTseng** [comment]
Received!

**Comment by bitcoinuser** [comment]
Same when we expand an image and click android back button.

https://github.com/user-attachments/assets/e96bf510-5419-44bc-8e7b-89aa37338977

**Comment by CodyTseng** [comment]
This is all because the website address didn't change. For the browser, there is no previous page, so it quit. I need to think about how to handle it.

**Comment by bitcoinuser** [comment]
Other example is zap window. Android back button make it close Jumble. On Nosotros client works great.

https://github.com/user-attachments/assets/832d0c3f-75b2-4928-b4e2-4059a252a5f6

https://github.com/user-attachments/assets/f68b67a8-96d1-4ac0-becc-b9440b519c0a

**Comment by bitcoinuser** [comment]
> Same when we expand an image and click android back button.
> 
>  Screenrecorder-2025-01-20-01-06-05-403.mp4

ditto.pub works as expected:

https://github.com/user-attachments/assets/3689685a-bb3f-4634-8bf2-d64a63728450

**Comment by CodyTseng** [comment]
I understand. This is all because Jumble doesn’t modify the URL when opening a dialog, and the browser relies on the URL to navigate. It doesn’t know it’s a dialog, haha. I'll find some time to fix these kinds of issues together.

**Comment by bitcoinuser** [comment]
> I understand. This is all because Jumble doesn’t modify the URL when opening a dialog, and the browser relies on the URL to navigate. It doesn’t know it’s a dialog, haha. I'll find some time to fix these kinds of issues together.

Same for this window: 

![Image](https://github.com/user-attachments/assets/c0868aaf-91fc-4600-b22a-4eba54f08abd)

**Comment by CodyTseng** [comment]
fixed in the beta version

**Comment by bitcoinuser** [comment]
Hi @CodyTseng I found one issue still here. This is the case:

https://github.com/user-attachments/assets/4359408c-865c-46e1-8c27-145df18f5030

**Comment by bitcoinuser** [comment]
> Hi [@CodyTseng](https://github.com/CodyTseng) I found one issue still here. This is the case:
> 
>  Screenrecorder-2025-05-06-13-11-23-400.mp4

This is the last remaining bug with android back button, haha.

**Comment by bitcoinuser** [comment]
> > > Hi [@CodyTseng](https://github.com/CodyTseng) I found one issue still here. This is the case:
> > > Screenrecorder-2025-05-06-13-11-23-400.mp4
> > 
> > 
> > This is the last remaining bug with android back button, haha.
> 
> Received

Fixed.
