### ISSUE TITLE
Cache should be updated whenever the user profile is viewed.

### ISSUE THREAD

**Issue by bitcoinuser** [CodyTseng/jumble#340]
Hi,

Cache should be updated whenever the user profile is viewed. 

Context: nevent1qvzqqqqqqypzpqf9hyg76r55m03spzstujx0uhxsczc9jg70l7gh4elg0k5yqzyrqyg8wumn8ghj7mn0wd68ytnddakj7qgkwaehxw309ahx7um5wgkhyetvv9ujuctswqhsqg8dw7q8ty77cg6a9nxpjjs3fk6k49taqlked7wuqjzlyn2h0dr2wcct4n2l

Thanks

**Comment by CodyTseng** [comment]
Fixed

**Comment by bitcoinuser** [comment]
Strange, I updated Jumble and still can't see the notes from nostr:npub1ggfzdxa8xrrzhaut6venkrmjtw8wl25y6l0wramkc7d4dlyaflzsxxrfcq

**Comment by bitcoinuser** [comment]
> Hum, on mobile I can see, but on Desktop no.

Any idea why @CodyTseng? Thanks.

**Comment by bitcoinuser** [comment]
> The only problem is that it has 13 relays but shows 15 here:
> 
> ![Image](https://github.com/user-attachments/assets/f6f17c01-0428-42c1-8661-dfe13f0290bd)

cc @CodyTseng

**Comment by bitcoinuser** [comment]
Ok, now changed to 13 relays.

**Comment by CodyTseng** [comment]
For a better user experience, Jumble still prioritizes using cached data. When you view someone's profile, Jumble updates the cache, and the changes will take effect the next time you view it.
